version: '3'
services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  app:
    build: .
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-chrome:4444/wd/hub
    depends_on:
      - selenium-chrome
    volumes:
      - ./allure-results:/app/allure-results
    command: pytest --alluredir=/app/allure-results
